### ISSUE TITLE
Error: Unknown state for task

### ISSUE THREAD

**Issue by vjoao** [matrix-io/matrix-firebase#17]
When trying to create a simulation device with `matrix sim init` the queue enters a wrong state: ` state: 'device-provisioning-in-progress'` and fails with `Error: Unknown state for task`.

Here is my stack trace:
```
Creating  { name: 'defaultSim', description: '' } [sim-214ec4cdda9625ce117d51096]
 Device registration request formed...
 Registering device...
 Device registered succesfuly
Error creating device defaultSim:  { Error: Unknown state for task -KeTQV2D-wQJx_vuhvkW
    at C:\Users\Victor\AppData\Roaming\npm\node_modules\matrix-cli\node_modules\matrix-firebase\lib\queue.js:149:32
    at C:\Users\Victor\AppData\Roaming\npm\node_modules\matrix-cli\node_modules\firebase\database-node.js:162:614
    at rb (C:\Users\Victor\AppData\Roaming\npm\node_modules\matrix-cli\node_modules\firebase\database-node.js:61:165)
    at Ob (C:\Users\Victor\AppData\Roaming\npm\node_modules\matrix-cli\node_modules\firebase\database-node.js:49:215)
    at Pb (C:\Users\Victor\AppData\Roaming\npm\node_modules\matrix-cli\node_modules\firebase\database-node.js:48:701)
    at Ue.h.Eb (C:\Users\Victor\AppData\Roaming\npm\node_modules\matrix-cli\node_modules\firebase\database-node.js:231:287)
    at Qg.h.ud (C:\Users\Victor\AppData\Roaming\npm\node_modules\matrix-cli\node_modules\firebase\database-node.js:207:251)
    at De.ud (C:\Users\Victor\AppData\Roaming\npm\node_modules\matrix-cli\node_modules\firebase\database-node.js:110:364)
    at $c.Vf (C:\Users\Victor\AppData\Roaming\npm\node_modules\matrix-cli\node_modules\firebase\database-node.js:108:281)
    at cd (C:\Users\Victor\AppData\Roaming\npm\node_modules\matrix-cli\node_modules\firebase\database-node.js:68:109) state: 'device-provisioning-in-progress' }
```

**Comment by eighteyes** [comment]
Hi @vjoao This issue should be filed against the `matrix-cli` repository. https://github.com/matrix-io/matrix-cli

Thanks, and just fyi, we're pushing hard on core features, the simulator has to be a lower priority for us right now, so we might not get to this for a few weeks.
